/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Mode {
  DEVELOPMENT = 0,
  PRODUCTION = 1
}
export const enum Target {
  ES3 = 0,
  ES5 = 1
}
export interface Module {
  generator?: Callback
  test: string
}
export interface BindingOptions {
  mode: Mode
  targets: Array<Target>
  context: string
  module: Module
}
export function build(options: BindingOptions): void
